CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL,
  "role" int NOT NULL,
  "course" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar,
  "level" int NOT NULL,
  "teacher" int NOT NULL,
  "category" int NOT NULL,
  "video" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" varchar NOT NULL,
  "url" varchar NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(20) NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "lastname" varchar(25) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL
);

CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role") REFERENCES "role" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("video") REFERENCES "course_videos" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "teachers" ("id");

INSERT INTO course_videos (filename, url) VALUES ('history video', 'www.history.com/krbkb'), ('biology video', 'www.biology.com/kjbgger');

INSERT INTO categories (name) VALUES ('History'), ('Biology');

INSERT INTO teachers (name, lastname) VALUES ('Juanito', 'Perez'), ('Juanita', 'Gonzalez');

INSERT INTO levels (level) VALUES ('Beginner'), ('Intermediate'), ('Advanced');

INSERT INTO role (name) VALUES ('Student'), ('Teacher'), ('Administrator'), ('Substitute');

INSERT INTO courses (title, description, level, teacher, category, video) VALUES ('Basic History Course', 'Learn the basics with us!', 1, 1, 1, 1);
INSERT INTO courses (title, description, level, teacher, category, video) VALUES ('Advanced Biology Course', 'Master your Biology knowledge with us!', 3, 2, 2, 2);

INSERT INTO users (name, email, password, age, role, course) VALUES ('Pedro Hernandez', 'pher@gmail.com', 'i5hlh5t', 30, 1, 2);
INSERT INTO users (name, email, password, age, role, course) VALUES ('Jordan Well PhD', 'histnk@school.com', 'histiufk542', 55, 2, 2);